# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c74749584bf0e420f48b43a952a090e22dbe2d35d377d5e73cb8b4e4123a70f417311e5cc72ad17c06762c47737dffdfc2b74776bd7f741353cc709bb9659e38

test:
  secret_key_base: 8e3ddb4a61d47fe53ec7813392ffff338e1801dd1a6f7c7cd71a4fe45d2b373d4baa64d4b2f3f2214fadbb02ec6151892c748ed796bb4bcec3e37b0b33b7a2b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
